CREATE TABLE	USUARIO(
	CODIGO		VARCHAR(10)	NOT NULL,
	EDAD		NUMERIC(2)	NOT NULL, 
	USERNAME	VARCHAR(20)	NOT NULL,
	NOMBRE		VARCHAR(30)	NOT NULL,
	APELLIDO	VARCHAR(30)	NOT NULL,
	PASSWORD	VARCHAR(30)	NOT NULL,
	EMAIL		VARCHAR(50)	NOT NULL,
	PRIMARY KEY	(CODIGO)
);
CREATE TABLE	GENERO(
	CODIGO			VARCHAR(5) 	NOT NULL,
	NOMBRE_GENERO	VARCHAR(20) NOT NULL,
	PRIMARY KEY	(CODIGO)
);

CREATE TABLE	PELICULA(
	CODIGO		VARCHAR(10)	NOT NULL,
	NOMBRE		VARCHAR(50)	NOT NULL,
	GENERO		VARCHAR(5)	NOT NULL,
	DURACION	FLOAT		NOT NULL,
	PRIMARY KEY	(CODIGO),
	CONSTRAINT	FK_CGENERO	FOREIGN KEY	(GENERO)	REFERENCES	GENERO(CODIGO)
);
	
CREATE TABLE	ACTOR(
	CODIGO		VARCHAR(10) NOT NULL,
	NOMBRE		VARCHAR(20) NOT NULL,
	APELLIDO	VARCHAR(20) NOT NULL,
	EDAD		NUMERIC(2)  NOT NULL,
	PRIMARY	KEY	(CODIGO)
);

CREATE TABLE	CASTING(
	CODIGO_ROL	VARCHAR(5) 	NOT NULL,
	CACTOR		VARCHAR(10)	NOT NULL,
	CPELICULA	VARCHAR(10)	NOT NULL,
	ROL			VARCHAR(30)	NOT NULL,
	PRIMARY KEY	(CODIGO_ROL),
	CONSTRAINT	FK_CCACTOR		FOREIGN KEY	(CACTOR)	REFERENCES	ACTOR(CODIGO),
	CONSTRAINT	FK_CCPELICULA	FOREIGN KEY	(CPELICULA)	REFERENCES	PELICULA(CODIGO)
);

CREATE TABLE ver
(
    cusuario  VARCHAR(10) 				NOT NULL,
    cpelicula VARCHAR(10) 				NOT NULL,
    duracion  numeric					NOT NULL,
    fecha     date 						NOT NULL,
    hora      time without time zone 	NOT NULL,
	CONSTRAINT	fk_vcusuario	FOREIGN KEY	(cusuario)	REFERENCES	usuario(codigo),
	CONSTRAINT	fk_vcpelicula	FOREIGN KEY	(cpelicula)	REFERENCES	pelicula(codigo),
    PRIMARY KEY (cusuario, cpelicula, fecha, hora)
)

CREATE TABLE perfiles
(
	cusuario  	VARCHAR(10) 			NOT NULL,
	profilename	VARCHAR(10) 			NOT NULL,
	edad	  	numeric					NOT NULL,
	Lognumber	numeric					NOT NULL,
	CONSTRAINT	fk_vcusuario	FOREIGN KEY	(cusuario)	REFERENCES	usuario(codigo),
	PRIMARY KEY (cusuario, profilename)
)

