CREATE TABLE	USUARIO
(
	CUSUARIO	VARCHAR			NOT NULL,
	USERNAME	VARCHAR			NOT NULL,
	NOMBRE		VARCHAR			NOT NULL,
	PASSWORD	VARCHAR			NOT NULL,
	EMAIL		VARCHAR			NOT NULL,
	CUENTA		VARCHAR			NOT NULL,
	PRIMARY KEY	(CUSUARIO)
);

CREATE TABLE	PELICULA
(
	CPELICULA		VARCHAR		NOT NULL,
	NOMBRE			VARCHAR		NOT NULL,
	DURACION		FLOAT		NOT NULL,
	CLASIFICACION 	INTEGER		NOT NULL,
	IMAGEN			VARCHAR		NOT NULL,
	LINK			VARCHAR		NOT NULL,
	DIRECTOR		VARCHAR		NOT NULL,
	PRIMARY KEY	(CPELICULA)
);
	
CREATE TABLE	ACTOR
(
	CPELICULA	VARCHAR 	NOT NULL,
	NOMBRE		VARCHAR  	NOT NULL,
	PRIMARY	KEY	(CPELICULA, NOMBRE),
	CONSTRAINT	FK_CCPELICULA	FOREIGN KEY	(CPELICULA)	REFERENCES	PELICULA(CPELICULA)
);

CREATE TABLE	GENERO
(
	CPELICULA	VARCHAR 	NOT NULL,
	GENERO		VARCHAR		NOT NULL,
	PRIMARY KEY	(CPELICULA, GENERO),
	CONSTRAINT	FK_CCPELICULA	FOREIGN KEY	(CPELICULA)	REFERENCES	PELICULA(CPELICULA)
);

CREATE TABLE 	ANUNCIOS
(
    CANUNCIO  	VARCHAR 	NOT NULL,
    ANUNCIO 	VARCHAR 	NOT NULL,
    ANUNCIANTE  VARCHAR		NOT NULL,
    PRIMARY KEY (CANUNCIO)
);

CREATE TABLE	ADBREAK
(
	CPELICULA	VARCHAR 	NOT NULL,
	CANUNCIO	VARCHAR		NOT NULL,
	PRIMARY KEY	(CPELICULA, CANUNCIO),
	CONSTRAINT	FK_CCPELICULA	FOREIGN KEY	(CPELICULA)	REFERENCES	PELICULA(CPELICULA),
	CONSTRAINT	FK_CCANUNCIO	FOREIGN KEY	(CANUNCIO)	REFERENCES	ANUNCIOS(CANUNCIO)
);

CREATE TABLE 	PERFIL
(
	CPERFIL		VARCHAR		NOT NULL,
	CUSUARIO 	VARCHAR		NOT NULL,
	LOGNUMBER	INTEGER		NOT NULL,
	PROFILENAME	VARCHAR 	NOT NULL,
	EDAD	  	INTEGER		NOT NULL,
	
	CONSTRAINT	fk_vcusuario	FOREIGN KEY	(cusuario)	REFERENCES	usuario(cusuario),
	PRIMARY KEY (CPERFIL)
);

CREATE TABLE	FAVORITOS
(
	CPERFIL		VARCHAR 	NOT NULL,
	CPELICULA	VARCHAR		NOT NULL,
	PRIMARY KEY	(CPERFIL, CPELICULA),
	CONSTRAINT	FK_CCPELICULA	FOREIGN KEY	(CPELICULA)	REFERENCES	PELICULA(CPELICULA),
	CONSTRAINT	FK_CCPERFIL		FOREIGN KEY	(CPERFIL)	REFERENCES	PERFIL(CPERFIL)
);

CREATE TABLE	VER
(
	CPERFIL		VARCHAR 	NOT NULL,
	CPELICULA	VARCHAR		NOT NULL,
	DURACION 	FLOAT		NOT NULL,
	FECHA		DATE 		NOT NULL,
	PRIMARY KEY	(CPELICULA, CPERFIL, FECHA),
	CONSTRAINT	FK_CCPELICULA	FOREIGN KEY	(CPELICULA)	REFERENCES	PELICULA(CPELICULA),
	CONSTRAINT	FK_CCPERFIL		FOREIGN KEY	(CPERFIL)	REFERENCES	PERFIL(CPERFIL)
);

CREATE TABLE	LOGINLOG
(
	CODIGO		VARCHAR 	NOT NULL,
	UIngreso	VARCHAR 	NOT NULL,
	PIngreso	VARCHAR		NOT NULL,
	FECHA		Float 		NOT NULL,
	PRIMARY KEY	(CODIGO)
);

