


CREATE ROLE ADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO ADMIN;
GRANT ALL ON SEQUENCE history_mod_id_seq TO admin;


ALTER ROLE ADMIN
WITH CREATEROLE;

CREATE OR REPLACE FUNCTION CREAR_ADMINS() 
RETURNS trigger AS $$
BEGIN
	IF NEW.CUENTA ILIKE 'ADMIN' THEN
		EXECUTE FORMAT('CREATE ROLE "%s"
					   LOGIN PASSWORD ''%s''; 
					   GRANT ADMIN TO "%s"', NEW.USERNAME, NEW.PASSWORD,NEW.USERNAME);
		RETURN NEW;
	END IF;
END;
$$ 
LANGUAGE PLPGSQL;

CREATE TRIGGER GIVE_ROLES
BEFORE INSERT ON USUARIO
FOR EACH ROW EXECUTE PROCEDURE CREAR_ADMINS();


