SELECT		WHO, COUNT(WHO) AS CANTIDAD
FROM		HISTORY_MOD
WHERE		TABNAME ILIKE 'usuario'
GROUP BY	WHO
ORDER BY	CANTIDAD DESC
LIMIT 5

INSERT INTO USUARIO(
	cusuario, username, nombre, password, email, cuenta)
VALUES (
	'U7','CAYOMOL01','Cayetano Moina','522fa1a6b36eb4500e5cd08aaf8150e50005390c3307940f0c9fc8c4c983fd1e','aaaaaaaa@gmail.com','Admin') 
;




SELECT * FROM pg_roles;

SELECT *
FROM HISTORY_MOD

CREATE ROLE ADMIN
GRANT ALL ON ALL TABLES IN SCHEMA "public" TO ADMIN
REVOKE ALL ON ALL TABLES IN SCHEMA "public"  FROM ADMIN

CREATE OR REPLACE FUNCTION CREAR_ADMINS() 
RETURNS trigger AS $$
BEGIN
	IF NEW.CUENTA ILIKE 'ADMIN' THEN
		EXECUTE FORMAT('CREATE ROLE "%s" 
					   WITH ADMIN 
					   LOGIN PASSWORD ''%s''; 
					   GRANT ADMIN TO "%s"', NEW.USERNAME, NEW.PASSWORD,NEW.USERNAME);
		RETURN NEW;
	END IF;
END;
$$ 
LANGUAGE PLPGSQL;

CREATE TRIGGER GIVE_ROLES
BEFORE INSERT ON USUARIO
FOR EACH ROW EXECUTE PROCEDURE CREAR_ADMINS();

GRANT ALL ON SEQUENCE history_mod_id_seq TO admin;

