DROP VIEW TOP10BUSQUEDA
CREATE VIEW TOP10BUSQUEDA
AS
SELECT 		DATO, COUNT(DATO) AS CANTIDAD
FROM 		BUSQUEDA
GROUP BY 	DATO
ORDER BY	CANTIDAD DESC
LIMIT 10




CREATE OR REPLACE FUNCTION TOP5ADMINS(FECHA_1 DATE,FECHA_2 DATE)
	RETURNS TABLE (
			USUARIO TEXT,
			CANTIDAD BIGINT
	) AS  $$
BEGIN
	RETURN QUERY
		SELECT		WHO, COUNT(WHO) AS CANTIDAD
		FROM		HISTORY_MOD
		WHERE		TABNAME ILIKE 'usuario'
		AND			TSTAMP::DATE > FECHA_1
		AND			TSTAMP::DATE < FECHA_2
		GROUP BY	WHO
		ORDER BY	CANTIDAD DESC
		LIMIT 5;
END;
$$
LANGUAGE PLPGSQL;




CREATE OR REPLACE FUNCTION PELICULAS_NOVISTAS(FECHA_1 DATE,FECHA_2 DATE)
	RETURNS TABLE (
			NOMBRE VARCHAR,
			CANTIDAD BIGINT
	) AS  $$
BEGIN
	RETURN QUERY
		SELECT NOMBRE, COUNT(NOMBRE) AS CANT
		FROM VER
		INNER JOIN PELICULA ON PELICULA.CPELICULA = VER.CPELICULA
		WHERE VER.DURACION/PELICULA.DURACION <1
		AND	  FECHA > FECHA_1 
		AND FECHA < FECHA_2
		AND   FECHA_2 - FECHA >=20
		GROUP BY NOMBRE
		ORDER BY CANT DESC
		LIMIT 20;
END;
$$
LANGUAGE PLPGSQL;



SELECT *
FROM PELICULA

